### ISSUE TITLE
Compatibility: Support more games (such as The Lost Vikings)

### ISSUE THREAD

**Issue by maximilien-noal** [OpenRakis/Spice86#107]
https://github.com/xor2003/masm2c/tree/master/qemu_tests

Other possible sources of inspiration :
https://github.com/nepx/halfix
https://github.com/86Box/86Box
https://github.com/jeffpar/pcjs/tree/master/machines/pcx86
https://github.com/dosbox-staging/dosbox-staging
https://github.com/mboros1/XTulator
https://github.com/gregdivis/Aeon
https://superfury.itch.io/unipcemu
https://github.com/sarah-walker-pcem/pcem

**Comment by maximilien-noal** [comment]
This could fix games such as The Lost Vikings.

**Comment by xor2003** [comment]
For Vikings there is non standard VGA mode 320x240, VGA scrolling, VGA split screen (configured over ports)

**Comment by xor2003** [comment]
[test-i386.zip](https://github.com/OpenRakis/Spice86/files/8867602/test-i386.zip)
Qemu tests converted into C#.
You can check if flags emulation is same as for qemu/dosbox

**Comment by maximilien-noal** [comment]
> [test-i386.zip](https://github.com/OpenRakis/Spice86/files/8867602/test-i386.zip) Qemu tests converted into C#. You can check if flags emulation is same as for qemu/dosbox

Thank you !
This is very valuable.
Once Dune is done (might take a while) this while help a lot in order to improve Spice86's compatibility with real mode DOS games.

**Comment by maximilien-noal** [comment]
Some issues to resolve in the far future (= when Dune is done) regarding compatibility:

- Support Floppy drive controller. Some games don't know what a hard disk is.
- Support PC boooters.
- Support for floppy image files. Some games had copy protection built into them. They won't work with a mounted directory as A:
- Support for MSCDEX
- Support for 16 MB of RAM
- x86 FPU
- 186, 286, 386, 486 instruction sets
- Protected mode
- V86 support (maybe, mght not be interesting for real mode DOS)
- TSR support
- Mouse callback support
- CGA
- EGA
- VGA Mode X, VGA scrolling, VGA split screen
- Joystick support (for games that are based on this method of input, ie. space simulations)
- Gravis Ultrasound support
- More Sound Blaster and OPL chips variants support (Sound Blaster Pro, 16, the original Sound Blaster...)
- Support for batch files, env vars

**Comment by maximilien-noal** [comment]
Meta issue: #308
