### ISSUE TITLE
Support for low-level C# code generation from ASM (Ghidra)

### ISSUE THREAD

**Issue by maximilien-noal** [OpenRakis/Spice86#19]
C# was chosen because it has keywords to replicate crazy x86 ASM, like the code found in Dune.
Things like goto.

Food for thoughts:

https://github.com/M-HT/SR
https://github.com/NationalSecurityAgency/ghidra/issues/1334
https://thecyberwire.com/stories/90782540555d4f49a4b00700ae4619fb/mike-bell-extending-ghidra-from-script-to-plugins-and-beyond

**Comment by maximilien-noal** [comment]
This will be implemented in Java, as Ghidra either supports Python or Java.

This issue is more of a reminder.

**Comment by maximilien-noal** [comment]
See also those projects :
https://github.com/gabonator/Education/tree/master/2021/CicoParser

DOSBox-X based IDA debugger
https://github.com/lab313ru/dsbxida

Translator from assembly code of the program into C language
https://github.com/xor2003/masm2c/issues/10

MASM2C:
https://github.com/xor2003/masm2c

**Comment by maximilien-noal** [comment]
https://github.com/frranck/asm2c

**Comment by xor2003** [comment]
I was able to convert stunts game. dune is next since it was dificulties

**Comment by kevinferrare** [comment]
This is mostly done via ghidra plugin https://github.com/OpenRakis/Spice86/blob/master/ghidraCodeGenerator/Spice86CodeGenerator.java
