### ISSUE TITLE
Alpha Waves / Continuum does not run.

### ISSUE THREAD

**Issue by maximilien-noal** [OpenRakis/Spice86#233]
**Describe the bug**

Alpha Waves / Continuum does not run.

It should:
https://www.mobygames.com/game/continuum/techinfo
Minimum CPU Class Required | Intel 8088 / 8086
Minimum OS Class Required | PC/MS-DOS 2.0
Minimum RAM Required | 512 KB
Media Type | 3.5" Floppy Disk,  5.25" Floppy Disk
Video Modes Supported | CGA, EGA, Hercules, Tandy / PCjr, VGA
Sound Devices Supported | Adlib, PC Speaker, Tandy / PCjr
Input Devices Supported | Keyboard
Controller Types Supported | Analog Joystick
Number of Offline Players | 1-2 Players

**To Reproduce**

Try to run it.

**Expected behavior**

**Comment by maximilien-noal** [comment]
It requires text mode first.

**Comment by maximilien-noal** [comment]
It throws an exception when callback 81 (0x51) is not found. In IndexBasedDispatcher

**Comment by LowLevelMahn** [comment]
i've got a re-assembled version that does not need the textmode but still needs EGA mode 0dh

**Comment by maximilien-noal** [comment]
Oh good !

Could you attach it to this issue, please ?

The service above that it does not find seems to be a DOS one that gives the crurent program PSP.

**Comment by maximilien-noal** [comment]
Oh good !

Could you attach it to this issue, please ?

The service above that it does not find seems to be a DOS one that gives the current program PSP.

**Comment by LowLevelMahn** [comment]
The original runs like that:

1. text-mode config program opens up
2. uncompress of PRGS1.CC -> extracting game exe for grafics-version + Sound-TSRs
3. Sound-TSRs are executed before game start (or else no sound) - dos int 21h/31h
4. setting of some interrupts
5. game start

**Comment by maximilien-noal** [comment]
Runs with corrupted graphics on master branch because EGA is not implemented (yet).
Runs with a black screen on the experimental more/graphics_modes branch,

**Comment by maximilien-noal** [comment]
Will implement EGA on a branch based from master. Should be simpler than figuring out more/graphics_mode just gets zeroes written to the video RAM.

On master there is no video RAM.
It's wrong for compatibility but it's easier to modify right now.

**Comment by LowLevelMahn** [comment]
i've just disassembled->reassembled the game exe (will release the assembler code later - stuill not shure if that is legayl) two weeks ago so im not super hardcore into the details of alpha waves but can more or less easily check every strange/unknown stuff you stumble over

**Comment by LowLevelMahn** [comment]
EGA/VGA start is always EGA-Mode 0dh (320x200x16)
