### ISSUE TITLE
InvalidOpCodeException: opcode=0xAF (No IMUL 32bit support)

### ISSUE THREAD

**Issue by JorisVanEijden** [OpenRakis/Spice86#259]
The following assembly:
```
1000:11AE 66 8B 46 0A                       mov     eax, [bp+arg_4]
1000:11B2 66 0F AF 46 0E                    imul    eax, [bp+arg_8]
1000:11B7 66 89 46 FC                       mov     [bp+var_4], eax
1000:11BB EB 63                             jmp     short loc_11220
```
Causes an InvalidOpCodeException: opcode=0xAF at 0x1000:0x11B2

The `0F AF` version of imul has not been implmented yet 
See: https://www.felixcloutier.com/x86/imul

**Comment by kevinferrare** [comment]
Looks like it is implemented now https://github.com/OpenRakis/Spice86/blob/master/src/Spice86.Core/Emulator/CPU/CPU.cs#L303
