### ISSUE TITLE
[BUG] Dune 2 mouse cursor doesn't move (because of missing mouse callback, or missing mouse driver)

### ISSUE THREAD

**Issue by maximilien-noal** [OpenRakis/Spice86#266]

**Comment by JorisVanEijden** [comment]
Is this still an issue?
The mouse cursor seems to move fine in Dune.
But not at all in Krondor :(

**Comment by maximilien-noal** [comment]
Yes indeed, this is still an issue.

Dune uses an older method compared to newer games.

I had a few shots at this, but didn't get very far due to lack of time.

**Comment by maximilien-noal** [comment]
Interesing code from JDOSBox related to this:

case CB_IRQ12:    // ps2 mouse int74
                if (!use_cb) Log.exit("int74 callback must implement a callback handler!");
                Memory.phys_writeb(physAddress, 0x1e);        // push ds
                Memory.phys_writeb(physAddress + 0x01, 0x06);        // push es
                Memory.phys_writew(physAddress + 0x02, 0x6066);    // pushad
                Memory.phys_writeb(physAddress + 0x04, 0xfc);        // cld
                Memory.phys_writeb(physAddress + 0x05, 0xfb);        // sti
                Memory.phys_writeb(physAddress + 0x06, 0xFE);        //GRP 4
                Memory.phys_writeb(physAddress + 0x07, 0x38);        //Extra Callback instruction
                Memory.phys_writew(physAddress + 0x08, callback);            //The immediate word
                return 0x0a;
            case CB_IRQ12_RET:    // ps2 mouse int74 return
                if (use_cb) {
                    Memory.phys_writeb(physAddress, 0xFE);    //GRP 4
                    Memory.phys_writeb(physAddress + 0x01, 0x38);    //Extra Callback instruction
                    Memory.phys_writew(physAddress + 0x02, callback);        //The immediate word
                    physAddress += 4;
                }
                Memory.phys_writeb(physAddress, 0xfa);        // cli
                Memory.phys_writew(physAddress + 0x01, 0x20b0);    // mov al, 0x20
                Memory.phys_writew(physAddress + 0x03, 0xa0e6);    // out 0xa0, al
                Memory.phys_writew(physAddress + 0x05, 0x20e6);    // out 0x20, al
                Memory.phys_writew(physAddress + 0x07, 0x6166);    // popad
                Memory.phys_writeb(physAddress + 0x09, 0x07);        // pop es
                Memory.phys_writeb(physAddress + 0x0a, 0x1f);        // pop ds
                Memory.phys_writeb(physAddress + 0x0b, 0xcf);        //An IRET Instruction
                return (use_cb ? 0x10 : 0x0c);

**Comment by maximilien-noal** [comment]
I implemented the missing code in the branch feature/mouse_callback

This is the only callback needed for Dune II according to my testing (disabling it in JDOSBox stops the mouse from moving), but it seems I just can't write it at the right addresses to save my life...

The latest code comes from DOSBox Staging.
