### ISSUE TITLE
VGA Renderer: IndexOutRangeException in some programs in GetDacPaletteColor (tested with Duke Nukem II)

### ISSUE THREAD

**Issue by maximilien-noal** [OpenRakis/Spice86#333]
**Describe the bug**

The start of Duke Nukem II produces a different kind of IndexOutRangeException in Renderer.cs on line 307 ("int fromPaletteRam6Bits = _state.AttributeControllerRegisters.InternalPalette[index];") :

```
private uint GetDacPaletteColor(int index) {
        switch (_state.AttributeControllerRegisters.AttributeControllerModeRegister.PixelWidth8) {
            case true:
                return _state.DacRegisters.ArgbPalette[index];
            default: {
                int fromPaletteRam6Bits = _state.AttributeControllerRegisters.InternalPalette[index];
                int bits0To3 = fromPaletteRam6Bits & 0b00001111;
                int bits4And5 = _state.AttributeControllerRegisters.AttributeControllerModeRegister.VideoOutput45Select
                    ? _state.AttributeControllerRegisters.ColorSelectRegister.Bits45 << 4
                    : fromPaletteRam6Bits & 0b00110000;
                int bits6And7 = _state.AttributeControllerRegisters.ColorSelectRegister.Bits67 << 6;
                int dacIndex8Bits = bits6And7 | bits4And5 | bits0To3;
                int paletteIndex = dacIndex8Bits & _state.DacRegisters.PixelMask;
                return _state.DacRegisters.ArgbPalette[paletteIndex];
            }
        }
    }
```

**To Reproduce**
1. Run Spice86 with this command line:
```
-d false --Ems -s
```
2. Program -> Start Program... -> Select NUKEM2.EXE

**Expected behavior**

Duke Nukem II should not produce this error.

**Screenshots**

![image](https://github.com/OpenRakis/Spice86/assets/1087524/c27f854b-5adc-4d91-bffc-7362efe7f3b7)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version: master commit b3a3de7

**Additional context**

state of local variables when the error occured:

```
bits0To3 = {int} 0 0x0
bits4And5 = {int} 0 0x0
bits6And7 = {int} 0 0x0
dacIndex8Bits = {int} 0 0x0
fromPaletteRam6Bits = {int} 0 0x0
index = {int} 197 0xC5
paletteIndex = {int} 0 0x0
```

The point at which the exception occurs is not always the same.

**Comment by JorisVanEijden** [comment]
Issue is caused by resolution changes during rendering (after the check if the buffer is large engough)

Proposed solution is to catch and ignore `IndexOutOfRangeException` during rendering. This will produce 1 slightly incomplete frame for 1/60th of a second.

**Comment by maximilien-noal** [comment]
Fixed via PR. https://github.com/OpenRakis/Spice86/pull/336
