### ISSUE TITLE
Translation testing: Port CryoDuneRE to .NET

### ISSUE THREAD

**Issue by maximilien-noal** [OpenRakis/Spice86#36]
This is to test what is presented in the readme, mainly the RunWithOverrides method.

It was translated from the original Java code, but not tested so far I believe.

**Comment by maximilien-noal** [comment]
The plan is still to superseed manual code rewrites with code generation. See this issue:
https://github.com/OpenRakis/Spice86/issues/19

**Comment by kevinferrare** [comment]
This is also because cryodunre methods are more readable than whatever would be generated with automated translation. Some methods would be tricky even with ASM-ish C#.
