### ISSUE TITLE
Dune 2: Intermission map mouse is too slow compared to real hardware or DOSBox

### ISSUE THREAD

**Issue by maximilien-noal** [OpenRakis/Spice86#367]
**Describe the bug**

The mouse moves too slowly compared to normal operation on real hardware (or DOSBox) in Dune 2's intermission screen.

**To Reproduce**
1. Play Dune 2.
2. Complete a mission.
3. Try to select a new mission area on the intermission screen.
4. See that the mouse cursor moves too slowly

**Expected behavior**

The mouse cursor should move at the same speed as when playing on real hardware.

**Comment by JorisVanEijden** [comment]
Is it the speed that is off? Or the range of movement?

**Comment by maximilien-noal** [comment]
Not reproduced anymore on latest master.
