### ISSUE TITLE
Grand Prix Circuit (1988): [WARN] [0xF000:0x20/0xF0020] Buffer size 64000 is too small for the required buffer size 288000 for render resolution 720 x 400

### ISSUE THREAD

**Issue by maximilien-noal** [OpenRakis/Spice86#371]

**Comment by JorisVanEijden** [comment]
It is normal for this to occur for a single frame due to timing issues between video mode changes and avalonia bitmap changes. This situaltion is simply ignored for a frame and should be resolved by the time the next frame is rendered.

This is only indicative of a problem if it occurs continously.

**Comment by maximilien-noal** [comment]
Thanks for clearing this up. :) 

I removed the bug label and closed this issue.
