### ISSUE TITLE
DOS INT 21 4E/4F File searching issues

### ISSUE THREAD

**Issue by JorisVanEijden** [OpenRakis/Spice86#383]
1. Search attributes passed into CX are not taken into account.
This makes it impossible to get directories included in the results.

2. The search for the next file should be based on the data in the 1st 21 bytes of the DosTransferArea.
And not on private state in C#.
This is what the TurboC library does on FindFirst:
- it reserves a data block for search results
- it sets the DTA to that block
- it performs a search
- it restores the original DTA
On FindNext is does:
- it takes any previously used datablock from a `FindFirst`
- it sets the DTA to that block
- it performs a search
- it restores the original DTA

This means it can have several different searches active at the same time, in different states.

See here for the full DTA data used by the FindFirst and FindNext calls: https://www.ctyme.com/intr/rb-2977.htm
```
Format of FindFirst data block:

Offset  Size    Description     (Table 01626)
---PC-DOS 3.10, PC-DOS 4.01, MS-DOS 3.2/3.3/5.0---
00h    BYTE    drive letter (bits 0-6), remote if bit 7 set
01h 11 BYTEs   search template
0Ch    BYTE    search attributes
---DOS 2.x (and some DOS 3.x???)---
00h    BYTE    search attributes
01h    BYTE    drive letter
02h 11 BYTEs   search template
---DOS 2.x and most 3.x---
0Dh    WORD    entry count within directory
0Fh    DWORD   pointer to DTA???
13h    WORD    cluster number of start of parent directory
---PC-DOS 4.01, MS-DOS 3.2/3.3/5.0---
0Dh    WORD    entry count within directory
0Fh    WORD    cluster number of start of parent directory
11h  4 BYTEs   reserved
---all versions, documented fields---
15h    BYTE    attribute of file found
16h    WORD    file time (see #01665 at AX=5700h)
18h    WORD    file date (see #01666 at AX=5700h)
1Ah    DWORD   file size
1Eh 13 BYTEs   ASCIZ filename+extension
```

**Comment by maximilien-noal** [comment]
The first part is fixed in the fix/dos_find_files branch:  https://github.com/OpenRakis/Spice86/pull/420

More later when the PR is ready.

I have high hopes that this will be fixed very soon.
