### ISSUE TITLE
Mainwindow is sometimes transparent (Windows) 

### ISSUE THREAD

**Issue by maximilien-noal** [OpenRakis/Spice86#387]
**Describe the bug**

Since the migration to AvaloniaUI v11, Spice86 on Windows has a transparent window. It happens for a single frame every now and then. 

**To Reproduce**
1. Startup the app on Windows 
2. See that the main window is transparent 

**Expected behavior**

The window should never be transparent. 

**Screenshots**
(todo) 

 - OS: Windows 
 - Version latest master 

**Additional context**
This is related to the app.manifest.

**Comment by maximilien-noal** [comment]
Not reproduced anymore on Windows (tested in a VM)

@JorisVanEijden  should this be closed ?

**Comment by JorisVanEijden** [comment]
I don't think I've seen it happen recently.
