### ISSUE TITLE
UI: A button to dump everything

### ISSUE THREAD

**Issue by kevinferrare** [OpenRakis/Spice86#44]
Would be nice to be able to dump everyting from the UI without having to go through GDB.
This implies a command line switch to turn on analysis at startup

**Comment by maximilien-noal** [comment]
For the UI, just invoke the code from the -d command line option.

**Comment by maximilien-noal** [comment]
Implemented. : https://github.com/OpenRakis/Spice86/commit/621f6c21534c37852592d4604ffee760afb78a73
