### ISSUE TITLE
Incorrect CRT rerfresh timings

### ISSUE THREAD

**Issue by maximilien-noal** [OpenRakis/Spice86#559]
**Describe the bug**

The VGA 0x3DA port is used by LOGO for proper timings. Somehow, the timings seems to be wrong.

This makes LOGO (from the floppy version of DUNE) animation fly by way too fast.

**To Reproduce**

Take DUNE (floppy version) and launch LOGO.EXE

**Expected behavior**

LOGO loops repeatedly waiting for the 3DA port to report the end of the retrace before drawing on the screen again, the animation should be way slower.

**Additional context**

Git bisect reveals the following:

first bad commit: 72bd31e584b02bda8916edf9323fdda3b80957f0

first good commit: 23ed90b9cd4141a668c17686d3f0e8cd5dca6371

Before this commit, the Timer class was calling _vgaCard.TickRetrace() to ensure proper timings.

Now this method does not exist anymore, as this responsibility lives in Renderer.cs. Alas, the code seems A-OK to me, and I can't fix it.

Also, the animations of menus in Dune (CD version, at least) ARE accurate. So far it seems to "only" affect LOGO.EXE

@JorisVanEijden Can I assign this bug to you ?

**Comment by maximilien-noal** [comment]
https://github.com/OpenRakis/Spice86/assets/1087524/81c5543f-1d28-4fc4-a8db-d536e43a6d8a

**Comment by JorisVanEijden** [comment]
`Spice86.Core.Emulator.InterruptHandlers.Timer.TimerInt8Handler.Run()` was mistakenly applying the PIT counter to the system timer, making it run backwards.
This caused LOGO to give up on detecting vsync too soon.
