### ISSUE TITLE
A new Script for Ghidra which detects code that Ghidra does not attach to a function (yet another Ghidra bug)

### ISSUE THREAD

**Issue by maximilien-noal** [OpenRakis/Spice86#95]
You have access to the list of functions
And to the list of instructions

for each instruction you look if it is in a function 
You keep a list of the ones that are not

the script inherits from GhidraScript which provides an API for this
In the generator, what can help:

* List of functions: FunctionIterator functionIterator = listing.getFunctions(true);
* List of address ranges by function: AddressSetView body = function.getBody()

For the instructions you can maybe browse the file in drone mode and for each address you look if there is an instruction or not: Instruction instruction = ghidraScript.getInstructionAt(min);
(copy and paste of the generator code so you can see the context)

**Comment by kevinferrare** [comment]
Algorithm would be as follow:
Create a map of function range start address to function range end address (iterate over all functions and all their ranges) called rangeMap

Iterate over the whole address space like so:
 - if there is an entry in rangeMap[address]
   -  address = rangeMap[address]
   -  address += instruction(address).length
 - else 
   - if there is an instruction, add its address to the result list
   - increment address

print the result list
